# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

lane :test_and_scan do
  scan(
    project: "BabyWize.xcodeproj",
      clean: true,
      concurrent_workers: 2,
      reset_simulator: true,
      force_quit_simulator: true,
      scheme: "BabyWize",
      devices: 'iPhone 14',
      code_coverage: true,
      output_style: "raw",
      result_bundle: "true",
      derived_data_path: "/Users/noam.efergan/Library/Developer/Xcode/DerivedData"
  )

end
end
