default_platform(:ios)

platform :ios do

lane :test_and_scan do
  scan(
    project: "BabyWize.xcodeproj",
      scheme: "BabyWize",
      device: 'iPhone 14',
      # derived_data_path: "~/Library/Developer/Xcode/DerivedData"
  )

end
end
